### ISSUE TITLE
Unique username prompt issues

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#101]
The unique username tick button dosen't always update to a cross when entering a username that has already been taken and the prompt (toast message) returned when choosing a username already taken is not correct.

**Comment by louisifn** [comment]
What username are you getting errors with that is taken?

The Cross is there to signify that the username is taken, giving a user a toast at every point would be annoying but i can add this in if we want it

**Comment by louisifn** [comment]
Similarly, for passwords, I have not given the user a toast for every character the password does not match, it does it for the first three letters

**Comment by profjb58** [comment]
Can't seem to re-produce it now, a bit weird.
All that needs to be added is a toast message saying 'username already taken'. Don't think the tick thing is too important for this.

**Comment by louisifn** [comment]
Still issue when username empty giving a positive response, others working

**Comment by louisifn** [comment]
Usernames now between 2 and 20 characters - fixed
