### ISSUE TITLE
UserInfoPrivate object not being passed back via an Intent to the main recipe info screen

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#104]
How to reproduce:
- Open edit profile
- Change filter settings
- Press back button

The filter settings don't update and unlike the simular issue whereby the recipe list dosen't refresh with the new settings for an entire session these filter settings wont be updated. IE only works on log out and back in.
This was broken somewhere along the way through one of the more recent pull requests but i'm happy to give it a stab tommorow since it's related to me branch.

**Comment by nathanbillis** [comment]
I think this is fixed on the maser but not sure

**Comment by nathanbillis** [comment]
No it’s not sorry people subscribed

**Comment by profjb58** [comment]
It does seem to be passing info back fine now. Tested with the debugger. The issue appears to be with #111 and is likely due to a new and recent addition

**Comment by profjb58** [comment]
Works on master, a non issue.
