### ISSUE TITLE
Adding photos to profile fails

### ISSUE THREAD

**Issue by nathanbillis** [SWEngGroup4/scranplan#109]
Going to edit profile, clicking to add photo, then trying to save the photo fails.

**Comment by profjb58** [comment]
Can't replicate this. Is there any more info on it?

**Comment by profjb58** [comment]
I know when it reaches 100% the progress bar dosen't dissapear though, that might be the issue.

**Comment by nathanbillis** [comment]
Edit profile > click on your profile pic > change it> click save settings> go to public profile

**Comment by profjb58** [comment]
Works for me.

**Comment by nathanbillis** [comment]
close and re-open the app

**Comment by nathanbillis** [comment]
doesn't get uploaded it's only updated locally

**Comment by profjb58** [comment]
Blimbey, thats a bit weird.

**Comment by nathanbillis** [comment]
the url for profile pic doesn't get updated in the firebase, it is uploaded tho

**Comment by profjb58** [comment]
Yeah just checked. Weird that. I'll fix it though, happened to be working on profile images anyway somehow.

**Comment by profjb58** [comment]
Yeah the filters, local image and privacy settings are not getting passed back via Intent.
Checked using the debugger. Must be an issue with recent social profile additions.

Also the private and public boxes don't sync properly now since that feature was removed. So i'll look into that as well.

**Comment by profjb58** [comment]
Fixed in the new branch i'm working on.
Issue was the image was getting uploaded after firebase updated with all it's info. Rookie mistake, lol.
Nothing to do with Louis stuff, has existed for a very long time, almost 3-4 weeks but because we only tried loading a local profile and I changed the system since it's been fixed.

**Comment by nathanbillis** [comment]
It’s not closed, please leave open as let git close it when you’ve made a PR with the fix 🙏

**Comment by profjb58** [comment]
> 
> 
> It’s not closed, please leave open as let git close it when you’ve made a PR with the fix 🙏

Oops. soz lol

**Comment by profjb58** [comment]
Fixed in #119
