### ISSUE TITLE
Adding any filter at all breaks searching + scrollviews

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#111]
**How to replicate**
- Set any dietary option or allegern option to true in the profile settings
- Log out and log back in again (Recipe info screen currently not updating correctly as well)
- Top picks and trending will be missing & searching will be impossible.

Assuming something in the more recent branches has broken this functionality.
Filters also shouldn't ever effect the ability to search for a chef.

**Comment by nathanbillis** [comment]
Really two seperate issues here, filtering breaking searching by chef and
dietary options not populating home screen queries. I can fix the searching
for chef quickly that’s just the case of removing the searchable attributes
from the query in searchQuery.java.

The other has nothing to do with searching and will take slightly longer.

**Comment by profjb58** [comment]
![Screenshot_20200529-110224_Scran Plan](https://user-images.githubusercontent.com/46009144/83247992-4d2d3580-a19c-11ea-92e8-b9f4fa203e1a.jpg)
Just so peeps know what i'm on about with the scrollviews failing. UserInfoPrivate data is correctly being sen't back, I have tested it using a debugger on master and this is a non-issue.

**Comment by nathanbillis** [comment]
fyi don't have to log out to reproduce, go to public profile then back again after making settings changes

**Comment by louisifn** [comment]
Sorted now, was just Firebase composite indexes for the new rating names

**Comment by nathanbillis** [comment]
Re opening until it gets closed with a pull request

**Comment by louisifn** [comment]
fair one but should be fixed on all branches as was backend issue

**Comment by nathanbillis** [comment]
Oh right didn’t realise that. You’re totally okay to close it 🙂
