### ISSUE TITLE
Profile setting page text view not resizing to text

### ISSUE THREAD

**Issue by louisifn** [SWEngGroup4/scranplan#118]
Text view to change about me does not resize, nor can the user scroll, thus making it unworkable
![Screenshot_20200529-193041](https://user-images.githubusercontent.com/49844440/83293075-221a0480-a1e3-11ea-8a16-1a79644f15ea.png)

**Comment by profjb58** [comment]
I'll see if I can limit it to 3 lines, if not then add a scrollview within it.

**Comment by profjb58** [comment]
Fixed on new bug fix branch i'm working on.
Has it the same size as before but the about me box expands vertically when u type more than 3 lines. Couldn't limit number of lines.
