### ISSUE TITLE
Clicking on a recipe from the recipe tab of a profile dosen’t work

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#122]
How to replicate.
- Go on your own or somebody else’s profile
- Go to the recipes section in the timeline
- Try to open one of the recipes.

**Comment by nathanbillis** [comment]
` holder.cardView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(mSearchListFragment != null && mDataset.get(position).document != null){
                    if(!mSearchListFragment.searchIndex.equals("SCRANPLAN_USERS")){
                    mSearchListFragment.recipeSelected(mDataset.get(holder.getAdapterPosition()).document);}
                    else if (mSearchListFragment.searchIndex.equals("SCRANPLAN_USERS")){
                        // When profile is selected
                        mSearchListFragment.profileSelected(mDataset.get(holder.getAdapterPosition()).document);
                    }
                }
                else if (mProfileRecipes != null){
                    mProfileRecipes.recipeSelected(mDataset.get(holder.getAdapterPosition()).document);
                }else{
                    Log.e("SEARCH RECYCLER ADAPTER", "Issue with no component in onBindViewHolder");
                }

            }
        });
`

**Comment by nathanbillis** [comment]
Something like this on line 123 in the search recycler adapter needs to be added but the fragment is coming from the profile page not home so launching will cause issues https://gist.github.com/nathanbillis/03ae2c0269ad35d35bbdc6f19f1a54f2
