### ISSUE TITLE
Portions changing from 6 to 1

### ISSUE THREAD

**Issue by nathanbillis** [SWEngGroup4/scranplan#134]
When selecting a recipe and changing the portions to six, it's impossible to change back to one. Same issue with going from 10 down to 2.
Tested on Braised peas with bacon, lentils and cod. 
Amount of lentils also remains the same, after setting to any portion other than it's original then changing. Launch a recipe and have a go hopefully you'll see what I mean!

**Comment by nathanbillis** [comment]
The lentil bug occurs for Tomato and thyme cod too this time for chopped tomatoes where it's locked to '1,000g can' (serving 10 going to 4/2/1 etc) with it originally being 400g can serving 4.

**Comment by nathanbillis** [comment]
[![Image from Gyazo](https://i.gyazo.com/ec15ada116e88ae5d3b900b114ba95e9.jpg)](https://gyazo.com/ec15ada116e88ae5d3b900b114ba95e9)
[![Image from Gyazo](https://i.gyazo.com/cede1bc6a9e03d93b09337fe0aff46c7.jpg)](https://gyazo.com/cede1bc6a9e03d93b09337fe0aff46c7)
[![Image from Gyazo](https://i.gyazo.com/cfd4247bbc5922829710390bc557d007.jpg)](https://gyazo.com/cfd4247bbc5922829710390bc557d007)
[![Image from Gyazo](https://i.gyazo.com/bf6aefa82213bf0d18649c34a7ab9fd6.jpg)](https://gyazo.com/bf6aefa82213bf0d18649c34a7ab9fd6)
[![Image from Gyazo](https://i.gyazo.com/d1ed176c5cf8ea575807aba171cda14b.jpg)](https://gyazo.com/d1ed176c5cf8ea575807aba171cda14b)
[![Image from Gyazo](https://i.gyazo.com/12135705eb36035b5e0bdf42f7159ae0.jpg)](https://gyazo.com/12135705eb36035b5e0bdf42f7159ae0)

**Comment by profjb58** [comment]
> When selecting a recipe and changing the portions to six, it's impossible to change back to one. Same issue with going from 10 down to 2.

Blimbey, thats a good spot. It's likely to do with a stray > or < operator where it should be equal to or less than / equal to or greater than. Hence not allowing you to convert.

**Comment by profjb58** [comment]
1,000g can > So there are a set of specific values that will always break portions. Another one is if a user uses two . values.

I think I explained the rogue inputs in the pull request It's very difficult to consider every type of string input so I need to either add that in when u create a recipe or create checks for if a conversion can't be done. The latter probably will be easier.

**Comment by profjb58** [comment]
Related pull request is #88

**Comment by profjb58** [comment]
Considering all invalid inputs I think I need to consider anything with...

- x2 or more full stops (decimal points)
- Fractions. Basic ones like 1/2 can probably be converted.
- , between numbers. Likely will just prevent portion conversions for this. May be able to remove it.
- x1, x2, x10 etc... multipliers.

I think it can be done but might take some time.
