### ISSUE TITLE
Filters incorrectly displayed

### ISSUE THREAD

**Issue by becky219** [SWEngGroup4/scranplan#135]
Vegan, vegetarian and pescatarian filters are all the wrong way round

**Comment by profjb58** [comment]
Do you have any more details on this. IE where there the wrong way around, a picture might help.

**Comment by nathanbillis** [comment]
It’s what we’re talking about on slack - if you search vegan in slack on
the coding channel you can find it I think

**Comment by profjb58** [comment]
Oh. In-correct filters for different recipes. Ok.
