### ISSUE TITLE
Create post button Overrides layout of whatever it's in

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#139]
**How to replicate**
Whilst not on the feed page...

- Click on the plus button at the bottom right
- Select 'create post'

![override](https://user-images.githubusercontent.com/46009144/83366793-242dc000-a3a9-11ea-8bbb-d340cae58466.gif)

**Comment by profjb58** [comment]
I think the issue seems to be new versions of RecipeFragment keep getting loaded in.
Setting RecipeFragment to null and reloading is a way of fixing it but it's not ideal. Ideally RecipeFragment shouldn't have to be reloaded within the Home fragment.

**Comment by jamesclawley** [comment]
Think this just a case of updating the tabs, the fragment is replaced correctly

**Comment by nathanbillis** [comment]
I'm working on a fix for this, by hiding the button when you're on meal planner/feed. Also fixing the transition error, where going from feed to meal planner causes it to slide the wrong way
