### ISSUE TITLE
User preferences not displaying in search settings

### ISSUE THREAD

**Issue by louisifn** [SWEngGroup4/scranplan#155]
![Screenshot_20200602-123845](https://user-images.githubusercontent.com/49844440/83515951-1aea4380-a4ce-11ea-8e2b-40159ccc0d66.png)
![Screenshot_20200602-123835](https://user-images.githubusercontent.com/49844440/83515952-1b82da00-a4ce-11ea-9691-d31152e9f7bc.png)

**Comment by nathanbillis** [comment]
@profjb58 think this it to do with #137

**Comment by profjb58** [comment]
Yeah so the filter search stuff isn’t updated currently. I don’t think it’s related to 137 which fixes the search options not staying retained when switching activities.
I can implement this very easy due to the alterations I’ve made but I’ll do it later today so I can get the audio timer stuff out the way.

**Comment by louisifn** [comment]
This entire issue is due to loadSearchOptions(); function

**Comment by louisifn** [comment]
Guessing this was what was added with #137?

**Comment by louisifn** [comment]
Ive fixed the issue removing the use of loadSearchOptions() for getSharedPreferences on onResume -> this function was not operating

Replacing this with:
if(mUser != null){
            mPescatarianBox.setChecked(mUser.getPreferences().isPescatarian());
            mVegetarianBox.setChecked(mUser.getPreferences().isVegetarian());
            mVeganBox.setChecked(mUser.getPreferences().isVegan());
            mNutsBox.setChecked(mUser.getPreferences().isAllergy_nuts());
            mEggsBox.setChecked(mUser.getPreferences().isAllergy_eggs());
            mMilkBox.setChecked(mUser.getPreferences().isAllergy_milk());
            mWheatBox.setChecked(mUser.getPreferences().isAllergy_gluten());
            mShellfishBox.setChecked(mUser.getPreferences().isAllergy_shellfish());
            mSoyBox.setChecked(mUser.getPreferences().isAllergy_soya());
        }
has the desired effect or reloading those checkboxes when anything changes in profile setting too

I feel there is now no use of the shared preferences though?
