### ISSUE TITLE
Initial preferences skip button dosen't skip

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#49]
When pressing the skip button on first register the user goes to the MainActivity.java page and hangs at the scranplan logo.

Think this is some issue to do with what happened when we moved the MainActivity and Home classes around.

**Comment by louisifn** [comment]
Fixed in C29

**Comment by profjb58** [comment]
@louisifn

**Comment by profjb58** [comment]
Is still fixed. Lol
