### ISSUE TITLE
Recipe info unable to load (Null object reference)

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#56]
Crashes on the following line at the 'reheat' instructions.

![image](https://user-images.githubusercontent.com/46009144/77852589-5a976500-71d7-11ea-80cd-0fc9c23ff380.png)
(Line 589, RecipeFragment.class.)

Crash report:
```
![image](https://user-images.githubusercontent.com/46009144/77852625-8b779a00-71d7-11ea-9186-f25cfbe26f5c.png)
```

Best estimate of whats going on is it needs to check for if the user is within the mealplanner screen or not. Best done by extending the current class to include the meaplanner stuff. This hasn't yet been done so the checks I think are failing

**Comment by nathanbillis** [comment]
What do you do to make this crash?

**Comment by profjb58** [comment]
just by logging in and selecting any particular recipe from the recipe list.

**Comment by nathanbillis** [comment]
I can't reproduce it, this is my device running on the master: 

![Alt Text](https://media.giphy.com/media/Id0V7ZJGsxhHn63hkg/giphy.gif)

**Comment by profjb58** [comment]
It wasn't crashing on mine either before but after messing with the mealplanner a bit it crashed,

**Comment by nathanbillis** [comment]
Okay, can you try uninstalling and reinstalling again, then making a new account and see if the issue persists?

**Comment by profjb58** [comment]
Sure yeah

**Comment by nathanbillis** [comment]
And re pulling from master

**Comment by profjb58** [comment]
Can't re-produce it now. Weird.
Just gonna close this and can re-open if it crops up again.
