### ISSUE TITLE
Timer appears on first slide

### ISSUE THREAD

**Issue by nathanbillis** [SWEngGroup4/scranplan#57]
Timer appears on the first slide of the presentation. #55 was approved due to this bug being non-fatal and documentation updated. 

**How to reproduce**
- [ ] Click on a recipe
- [ ] Click lets cook
- [ ] First slide has timer on

**Comment by profjb58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timer - Appearing on first slide regardless](https://trello.com/c/e4sqD6hr/68-timer-appearing-on-first-slide-regardless)

**Comment by profjb58** [comment]
Fixed alongside new update to Espresso timer tests.
Will add the pull request in the morning.

**Comment by profjb58** [comment]
Added the pull request anyway because I can explain what i've worked on in the morning anyway.
Pull request reference is: #80
