### ISSUE TITLE
layout issues with query selector 

### ISSUE THREAD

**Issue by nathanbillis** [SWEngGroup4/scranplan#60]
Initially in #53, but this is for the layout issues @profjb58 found.

![image](https://user-images.githubusercontent.com/4777332/77896027-882fed00-726f-11ea-9cbb-383cfd6463a5.png)

**Comment by profjb58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Query selector layout issues](https://trello.com/c/msSCzbQA/64-query-selector-layout-issues)

**Comment by profjb58** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/46009144/79174976-44eb8780-7df4-11ea-884d-b8e350828f6c.png)

**Comment by nathanbillis** [comment]
Please leave Bugs open until the fix is added to the master :)
