### ISSUE TITLE
User searching

### ISSUE THREAD

**Issue by nathanbillis** [SWEngGroup4/scranplan#66]
Add functionality to search by user and display the public profile of user(s).

**Comment by nathanbillis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Searching - Extending searching to allow searching of user profiles](https://trello.com/c/kyZlnlwH/71-user-searching-extending-searching-to-allow-searching-of-user-profiles)

**Comment by profjb58** [comment]
Happy to go through this week if yer free Nathan. Could maybe pair program over skype since you have a good knowledge of Algolia and I can offer advice on the user collections and public profile contents and retrival.

**Comment by profjb58** [comment]
Fixed through the #106 branch.
![image](https://user-images.githubusercontent.com/46009144/83143094-57422c00-a0e9-11ea-94cb-31957e47f757.png)
