### ISSUE TITLE
Favourites star dosen't update

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#74]
When adding a recipe to favourites it would make sense for the star at the top to change colour or fill in. Currently it just sends a toast message.

**Comment by nathanbillis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [C9 - **Recipe Ratings** -As a user I can tap a rating under recipes to give them a star rating out of 5](https://trello.com/c/U5GyDXfn/29-c9-recipe-ratings-as-a-user-i-can-tap-a-rating-under-recipes-to-give-them-a-star-rating-out-of-5)

**Comment by profjb58** [comment]
@Jun0305 said this was fixed by @Jimb0nda
