### ISSUE TITLE
Mealplanner dosen't update upon changing preferences

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#86]
The main recipe screen updates properly but you can only update the MealPlanner upon logging out and back in again. I'm pretty sure this is because the userInfoPrivate object containing all local profile info isn't being passed upon switching tabs to the MealPlanner.
With a bit of debugging you could confirm if this is true or not quite easily.

Given i've been working with the Mealplanner I might be able to figure out how to fix this but this is more James Cs thing to fix I think.

**Comment by nathanbillis** [comment]
Is this the adding recipes from meal planner screen?

**Comment by profjb58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mealplanner doesn't update upon changing a users preferences.](https://trello.com/c/j9yTzxh9/77-mealplanner-doesnt-update-upon-changing-a-users-preferences)

**Comment by profjb58** [comment]
> Is this the adding recipes from meal planner screen?

yes.

**Comment by nathanbillis** [comment]
Fixed.
