### ISSUE TITLE
Changing profile photo on change settings

### ISSUE THREAD

**Issue by louisifn** [SWEngGroup4/scranplan#94]
Change Profile Settings - Load bar stays on 0% forever when attempting to upload a profile photo, when changing picture while loading bar present - causes loading bar to go but new settings can no longer be saved.

**Comment by profjb58** [comment]
I can't seem to replicate it. Definately don't get the issue with the progress bar staying at 0% forever. I do have an issue whereby it tries to re-upload the image if it's interrupted and if the image is a very large file it sometimes dosen't display the progress bar on the first save settings press though which is an issue. It does still upload the image though.

If you could send the exact steps required to re-produce this that would be helpful.

**Comment by profjb58** [comment]
0% issue doesn’t seem to be a thing but the issue whereby the progress bar doesn’t display is still a thing.
