### ISSUE TITLE
Delay deleting photos

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#95]
Deleting posts with photos close to the 4mb limit took up to about 10 seconds to delete on occasion on an actual testing device. Using the same loading screen when deleting a post might be an idea.

No gif/video, on an actual device with no screen capture available.

**Comment by louisifn** [comment]
Will try again with this one

**Comment by profjb58** [comment]
Given the number of other issues coming up and extra stuff to do for the presentation etc... might be worth leaving this and limiting photo uploads to about 2mb so it never takes too long to delete.
